### PR TITLE
fix type exports for plugin and support packages

### LINKED ISSUE #55: Types for plugin and support packages are exported incorrectly from respective package.json
### Before opening, please confirm:

- [X] I have searched for [duplicate or closed issues](https://github.com/currents-dev/cypress-debugger/issues) and [discussions](https://github.com/currents-dev/cypress-debugger/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I acknowledge that I will attach a **full debug log**, otherwise the issue will be closed with no response.

### Environment information

<details>

```
# Put output below this line
  System:
    OS: macOS 13.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 242.45 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.5.0 - ~/universe3/universe/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Safari: 16.6
  npmPackages:
    yup: 0.29.1 => 0.29.1
  npmGlobalPackages:
    corepack: 0.14.1
    npm: 8.19.2
    yarn: 1.22.18

```

</details>

### Describe the bug

When importing types from @currents/cypress-debugger-support and/or @currents/cypress-debugger-plugin, the types do not appear available.

This is happening because in each package's package.json. the `"types": "./src/index.ts"` should be instead `"types": "./dist/index.d.ts"`.

I will make a PR to address, but wanted to have the issue for tracking purposes.

### Expected behavior

The types should be available from these packages after installing.

### Command and Setup

<details>

### Command (share the exact `cypress` or `cypress-cloud` command you're running)        

```
# Put output below this line

N/A just for types

```

### Setup files cypress.config.j|ts|json

```
# Put output below this line

N/A just for types

```
</details>

### Full log and debug output

<details>

```
# Put your logs below this line

N/A just for types

```

</details>

### PR DESCRIPTION
**Pull request by Eric162**
Fixes #55

Basically the types output was incorrect, pointing to the source index.ts rather than the build types file.

### CODE REVIEW

**Comment by agoldis** [comment]
@Eric162 when publishing `package.json` is overriden by https://github.com/currents-dev/cypress-debugger/blob/main/packages/support/publish.js - are you still experiencing issues with types?

**Comment by Eric162** [comment]
@agoldis I see. Let me take a closer look at that.

But yes, i am still seeing issues - in the package.json of the version I have it looks like so:

```json
{
  "name": "@currents/cypress-debugger-plugin",
  "version": "1.0.7",
  "main": "./dist/index.js",
  "types": "./src/index.ts",
  "license": "GPL-3.0-or-later",
  "scripts": {
    "build": "tsup-node",
    "dev": "tsup --watch",
    "lint": "eslint src --fix",
    "publish-npm": "node ./publish.js",
    "test": "jest"
  },
  "keywords": [
    "cypress",
    "e2e",
    "cypress-debugger",
    "currents",
    "cypress-replay",
    "cypress-traces",
    "replay",
    "sorry-cypress",
    "time-travel"
  ],
  "files": [
    "dist",
    "LICENSE.md"
  ],
  "devDependencies": {
    "@types/chrome-remote-interface": "^0.31.9",
    "@types/debug": "^4.1.7",
    "tsconfig": "*",
    "tsup": "^6.6.3",
    "typescript": "^5.1.6"
  },
  "dependencies": {
    "@currents/cypress-debugger-support": "*",
    "@neuralegion/cypress-har-generator": "^5.16.4",
    "chrome-remote-interface": "^0.32.1",
    "debug": "^4.3.4"
  }
}
```

**Comment by Eric162** [comment]
Looks like the "exports" field only exists in the `dist` folder

the previous json i posted was from
`node_modules/@currents/cypress-debugger-plugin/package.json` **VS**
`node_modules/@currents/cypress-debugger-plugin/dist/package.json` :

```json
{
  "name": "@currents/cypress-debugger-plugin",
  "version": "1.0.7",
  "main": "./dist/index.js",
  "license": "GPL-3.0-or-later",
  "scripts": {
    "build": "tsup-node",
    "dev": "tsup --watch",
    "lint": "eslint src --fix",
    "publish-npm": "node ./publish.js",
    "test": "jest"
  },
  "keywords": [
    "cypress",
    "e2e",
    "cypress-debugger",
    "currents",
    "cypress-replay",
    "cypress-traces",
    "replay",
    "sorry-cypress",
    "time-travel"
  ],
  "files": [
    "*"
  ],
  "devDependencies": {
    "@types/chrome-remote-interface": "^0.31.9",
    "@types/debug": "^4.1.7",
    "tsconfig": "*",
    "tsup": "^6.6.3",
    "typescript": "^5.1.6"
  },
  "dependencies": {
    "@currents/cypress-debugger-support": "*",
    "@neuralegion/cypress-har-generator": "^5.16.4",
    "chrome-remote-interface": "^0.32.1",
    "debug": "^4.3.4"
  },
  "exports": {
    ".": {
      "import": "./index.mjs",
      "require": "./index.js",
      "types": "./index.d.ts"
    }
  }
}```

**Comment by Eric162** [comment]
One note is - we are not importing these packages directly (and don't really want to) - we are trying to use the types through the overall `cypress-debugger` package, but that package seems to point to the overall package.json rather than the dist folder's package.json, and so the types don't come through for us.

**Comment by Eric162** [comment]
maybe this

https://github.com/currents-dev/cypress-debugger/blob/main/packages/cypress-debugger/index.ts#L4-L5

would need to point to `/dist` ? trying some stuff locally to see

**Pull request closed without merging**
